import { useMemo, useState } from 'react'
import { AlertTriangle, BookOpenCheck, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Edit3, GraduationCap, ListChecks, MessageSquareText, Play, Plus, RefreshCw, Send, Sparkles, Target, Users, X } from './Icons'
import { GrowthReview, LearningAssignment, LearningSuggestion, WorkflowState, workflowApi } from '../data/workflowApi'

type Notify=(text:string)=>void
type StateSetter=(state:WorkflowState)=>void
const shortTime=(value:string)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))
const assignmentStatus:Record<LearningAssignment['status'],string>={assigned:'待学习',in_progress:'学习中',failed:'未达标待补学',leader_verification:'待班长验证',closed:'已闭环'}
const suggestionStatus:Record<LearningSuggestion['status'],string>={pending_training:'待培训受理',reviewing:'评估中',accepted:'已采纳',rejected:'已答复',closed:'已落地'}

function useLearningAction(setState:StateSetter,notify:Notify){
 const [busy,setBusy]=useState(false)
 const run=async(action:()=>Promise<WorkflowState>,success:string)=>{
  if(busy)return
  setBusy(true)
  try{const next=await action();setState(next);notify(success)}catch(error){notify(error instanceof Error?error.message:'学习成长流程处理失败')}finally{setBusy(false)}
 }
 return {busy,run}
}
export function TrainingLearningHub({state,setState,notify}:{state:WorkflowState|null;setState:StateSetter;notify:Notify}){
 const [tab,setTab]=useState<'banks'|'assignments'|'suggestions'|'growth'>('banks')
 const {busy,run}=useLearningAction(setState,notify)
 if(!state)return <div className="learning-loading"><RefreshCw size={18}/>正在读取学习成长状态…</div>
 const learning=state.learning
 const pendingAssignments=learning.assignments.filter(item=>item.status!=='closed').length
 const pendingSuggestions=learning.suggestions.filter(item=>['pending_training','reviewing','accepted'].includes(item.status)).length
 const pendingGrowth=learning.growthReviews.filter(item=>['planned','training_review'].includes(item.status)).length
 const firstDraft=learning.questionBanks.find(item=>item.status==='draft')
 return <section className="panel training-learning-hub">
  <header><div><span>培训生产深化 · 题库、场次、考试、成长追踪</span><h2>培训不是“讲过了”，要证明员工学会并在业务中改善</h2><p>课程有资源、考试有目标、班长验效果、员工能收到结果。</p></div><em>{pendingAssignments+pendingSuggestions+pendingGrowth}项待培训推进</em></header>
  <nav>
   <button className={tab==='banks'?'active':''} onClick={()=>setTab('banks')}><BookOpenCheck size={16}/>题库与场次 <b>{learning.questionBanks.filter(item=>item.status==='draft').length}</b></button>
   <button className={tab==='assignments'?'active':''} onClick={()=>setTab('assignments')}><GraduationCap size={16}/>个人学习 <b>{pendingAssignments}</b></button>
   <button className={tab==='suggestions'?'active':''} onClick={()=>setTab('suggestions')}><MessageSquareText size={16}/>员工建议 <b>{pendingSuggestions}</b></button>
   <button className={tab==='growth'?'active':''} onClick={()=>setTab('growth')}><Target size={16}/>30/60/90成长 <b>{pendingGrowth}</b></button>
  </nav>
  <div className="training-learning-body">
   {tab==='banks'&&<div className="learning-bank-grid"><section><header><div><span>知识版本治理</span><h3>题库发布必须满足数量与及格线</h3></div><button className="secondary" disabled={busy||!firstDraft} onClick={()=>firstDraft&&run(()=>workflowApi.learningBankAction(firstDraft.id,'update',{questionCount:firstDraft.targetQuestionCount,passingScore:firstDraft.passingScore}),'题库已补齐至发布目标')}><Plus size={14}/>补齐题目</button></header>{learning.questionBanks.map(bank=><article key={bank.id}><span className={`bank-state ${bank.status}`}>{bank.status==='published'?'已发布':bank.status==='retired'?'已停用':'草稿'}</span><div><strong>{bank.title}</strong><small>{bank.id} · {bank.version} · {bank.category}</small><div><i style={{width:`${Math.min(100,bank.questionCount/bank.targetQuestionCount*100)}%`}}></i></div></div><b>{bank.questionCount}/{bank.targetQuestionCount}题</b><em>及格 {bank.passingScore}</em>{bank.status==='draft'&&<button className="primary" disabled={busy||bank.questionCount<bank.targetQuestionCount} onClick={()=>run(()=>workflowApi.learningBankAction(bank.id,'publish'),'题库已发布，课程和考试现在可以使用')}>发布</button>}</article>)}</section><aside><header><span>讲师与教室资源</span><h3>今日培训场次</h3></header>{learning.sessions.map(session=>{const bank=learning.questionBanks.find(item=>item.id===session.bankId);return <article key={session.id}><div><strong>{session.title}</strong><small>{session.trainer} · {session.room}</small></div><span>{shortTime(session.startAt)}</span><p><b>{session.enrolled}/{session.capacity}人</b><em>出勤目标 ≥{session.targetAttendance}%</em></p><footer><span className={session.status}>{session.status==='planned'?'待开始':session.status==='running'?'进行中':`已完成 · ${session.attendanceRate}%`}</span>{session.status==='planned'&&<button disabled={busy||bank?.status!=='published'} onClick={()=>run(()=>workflowApi.learningSessionAction(session.id,'start'),'课程场次已开始并提醒参训员工')}><Play size={13}/>开始</button>}{session.status==='running'&&<button disabled={busy} onClick={()=>run(()=>workflowApi.learningSessionAction(session.id,'complete',99),'场次出勤达标，进入个人考试')}>完成场次</button>}</footer></article>})}</aside></div>}
   {tab==='assignments'&&<div className="learning-assignment-board"><div className="learning-assignment-head"><span>员工 / 班组</span><span>学习任务</span><span>目标与结果</span><span>状态</span><span>下一责任人</span><span>操作</span></div>{learning.assignments.map(item=><article key={item.id}><div><strong>{item.employeeName}</strong><small>{item.employeeId} · {item.team}</small></div><div><b>{item.title}</b><small>{item.source}</small></div><div><strong>{item.score||'—'} / {item.targetScore}分</strong><small>{item.improvementTarget}</small></div><em className={item.status}>{assignmentStatus[item.status]}</em><span>{item.status==='failed'?'培训主管':item.status==='leader_verification'?`${item.leader}班长`:item.status==='closed'?'已关闭':item.employeeName}</span><div>{item.status==='failed'&&<button disabled={busy} onClick={()=>run(()=>workflowApi.learningAssignmentAction(item.id,'training','reassign',{dueAt:new Date(Date.now()+24*60*60*1000).toISOString()}),'补学和补考已重新下发员工')}>安排补考</button>}{item.status==='closed'&&<CheckCircle2 size={18}/>}</div></article>)}</div>}
   {tab==='suggestions'&&<div className="learning-suggestion-board">{learning.suggestions.map(item=><article key={item.id}><header><div><span>{item.employeeName} · {item.team}</span><h3>{item.title}</h3></div><em className={item.status}>{suggestionStatus[item.status]}</em></header><p>{item.detail}</p>{item.response&&<aside><MessageSquareText size={15}/><span>{item.response}</span></aside>}<footer><small>{item.id} · {shortTime(item.createdAt)}</small><div>{item.status==='pending_training'&&<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.learningSuggestionAction(item.id,'start','已受理，正在评估课程与题库影响。'),'建议已受理并进入评估')}>受理建议</button>}{item.status==='reviewing'&&<><button className="secondary" disabled={busy} onClick={()=>run(()=>workflowApi.learningSuggestionAction(item.id,'reject','经核对当前课程已覆盖该场景，本次不重复增加；将补充知识卡片索引。'),'建议已形成答复')}>答复不采纳</button><button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.learningSuggestionAction(item.id,'accept','建议有明确一线价值，纳入下个题库版本和场景演练。'),'建议已采纳并回传员工')}>采纳</button></>}{item.status==='accepted'&&<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.learningSuggestionAction(item.id,'close','题库与场景练习已发布，员工可在个人任务中查看。'),'建议落地结果已回传员工')}>确认落地</button>}</div></footer></article>)}</div>}
   {tab==='growth'&&<div className="growth-review-board">{learning.growthReviews.map(review=><article key={review.id}><header><span><b>{review.milestone}</b>日</span><div><strong>{review.employeeName}成长评估</strong><small>{review.team} · 班长 {review.leader} · 截止{shortTime(review.dueAt)}</small></div><em>{review.status==='planned'?'待开始':review.status==='training_review'?'培训评估中':review.status==='leader_pending'?'待班长确认':'已完成'}</em></header><div>{review.metrics.map(metric=>{const met=metric.higherBetter?metric.actual>=metric.target:metric.actual<=metric.target;return <span className={met?'met':'gap'} key={metric.label}><small>{metric.label}</small><strong>{metric.actual}{metric.unit}</strong><em>目标 {metric.higherBetter?'≥':'≤'}{metric.target}{metric.unit}</em></span>})}</div>{review.trainingComment&&<p><b>培训意见：</b>{review.trainingComment}</p>}{review.status!=='closed'&&<footer>{['planned','training_review'].includes(review.status)?<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.growthReviewAction(review.id,'training','training_submit',`${review.milestone}日评估显示业务掌握与一次解决仍有差距，建议班长连续7日跟踪录音和个人目标。`),'成长评估已提交班长确认')}>提交阶段评估</button>:<span><Clock3 size={14}/>等待班长确认下一阶段目标</span>}</footer>}</article>)}</div>}
  </div>
 </section>
}

export function EmployeeLearningHub({state,setState,notify}:{state:WorkflowState|null;setState:StateSetter;notify:Notify}){
 const [examItem,setExamItem]=useState<LearningAssignment|null>(null)
 const [score,setScore]=useState(88)
 const [reflection,setReflection]=useState('我会先确认客户现有套餐与真实需求，再解释规则和办理结果，结束前让客户复述确认。')
 const [suggestionOpen,setSuggestionOpen]=useState(false)
 const [suggestionTitle,setSuggestionTitle]=useState('增加业务边界场景录音练习')
 const [suggestionDetail,setSuggestionDetail]=useState('建议增加客户打断、系统办理失败和承诺期争议三类真实脱敏录音，让学习任务更贴近一线场景。')
 const {busy,run}=useLearningAction(setState,notify)
 if(!state)return null
 const assignments=state.learning.assignments.filter(item=>item.employeeId==='JR10776')
 const suggestions=state.learning.suggestions.filter(item=>item.employeeId==='JR10776')
 const reviews=state.learning.growthReviews.filter(item=>item.employeeId==='JR10776')
 const closed=assignments.filter(item=>item.status==='closed')
 const ability={business:82+closed.reduce((sum,item)=>sum+item.abilityDelta.business,0),system:86+closed.reduce((sum,item)=>sum+item.abilityDelta.system,0),communication:79+closed.reduce((sum,item)=>sum+item.abilityDelta.communication,0)}
 const submitSuggestion=()=>{
  run(()=>workflowApi.createLearningSuggestion({category:'learning',title:suggestionTitle,detail:suggestionDetail}),'建议已提交培训岗位，1个工作日内受理')
  setSuggestionOpen(false)
 }
 return <section className="panel employee-learning-hub">
  <header><div><span>我的学习与能力档案</span><h2>学习任务必须服务于个人目标Gap</h2><p>考试证明“学会了”，班长验证“用出来了”。</p></div><button className="secondary" onClick={()=>setSuggestionOpen(true)}><Edit3 size={14}/>提业务或学习建议</button></header>
  <div className="employee-ability-strip"><article><span>业务能力</span><strong>{ability.business}</strong><i><b style={{width:`${ability.business}%`}}></b></i><small>目标 ≥90 · Gap {Math.max(0,90-ability.business)}分</small></article><article><span>系统操作</span><strong>{ability.system}</strong><i><b style={{width:`${ability.system}%`}}></b></i><small>目标 ≥88 · Gap {Math.max(0,88-ability.system)}分</small></article><article><span>沟通表达</span><strong>{ability.communication}</strong><i><b style={{width:`${ability.communication}%`}}></b></i><small>目标 ≥85 · Gap {Math.max(0,85-ability.communication)}分</small></article><aside><Sparkles size={18}/><div><b>AI成长建议</b><p>优先完成续约争议学习任务，可同时改善业务能力、沟通表达和重复来电率。</p></div></aside></div>
  <div className="employee-learning-layout"><section><header><span>个人任务</span><h3>{assignments.filter(item=>item.status!=='closed').length}项待完成</h3></header>{assignments.map(item=><article key={item.id}><span className={`learning-task-state ${item.status}`}>{item.status==='closed'?<CheckCircle2 size={16}/>:item.status==='failed'?<AlertTriangle size={16}/>:<BookOpenCheck size={16}/>}</span><div><strong>{item.title}</strong><small>{item.source}</small><p>{item.improvementTarget}</p><div><i style={{width:`${item.progress}%`}}></i></div></div><aside><em>{assignmentStatus[item.status]}</em><small>截止 {shortTime(item.dueAt)}</small>{['assigned','failed'].includes(item.status)&&<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.learningAssignmentAction(item.id,'employee','start'),'学习任务已开始')}>开始学习</button>}{item.status==='in_progress'&&<button className="primary" disabled={busy} onClick={()=>setExamItem(item)}>参加考试</button>}{item.status==='leader_verification'&&<span>考试 {item.score}分，等待{item.leader}验证</span>}</aside></article>)}</section><aside><header><span>我的建议</span><h3>一线声音有回执</h3></header>{suggestions.map(item=><article key={item.id}><div><strong>{item.title}</strong><em>{suggestionStatus[item.status]}</em></div><p>{item.response||'等待培训岗位受理'}</p></article>)}<header className="growth-title"><span>成长里程碑</span><h3>30 / 60 / 90日</h3></header>{reviews.map(review=><article className="employee-growth-card" key={review.id}><b>{review.milestone}日</b><div><strong>{review.status==='closed'?'评估已完成':review.status==='leader_pending'?'等待班长确认':'待阶段评估'}</strong><p>{review.trainingComment||'结合产能、质量和能力任务形成下一阶段目标。'}</p></div></article>)}</aside></div>
  {examItem&&<div className="learning-modal-backdrop" onClick={()=>setExamItem(null)}><section className="learning-modal" onClick={event=>event.stopPropagation()}><header><div><span>个人学习考试</span><h2>{examItem.title}</h2><p>目标分 {examItem.targetScore} · 第 {examItem.attempts+1} 次考试</p></div><button aria-label="关闭考试" onClick={()=>setExamItem(null)}><X size={18}/></button></header><div><label>考试成绩<input type="number" min="0" max="100" value={score} onChange={event=>setScore(Number(event.target.value))}/></label><label>学习复盘<textarea value={reflection} onChange={event=>setReflection(event.target.value)}/></label><aside><Target size={15}/>达标后进入班长业务验证；未达标自动返回培训补学。</aside></div><footer><button className="secondary" onClick={()=>setExamItem(null)}>取消</button><button className="primary" disabled={busy||reflection.trim().length<10} onClick={()=>{run(()=>workflowApi.learningAssignmentAction(examItem.id,'employee','submit',{score,reflection}),score>=examItem.targetScore?'考试达标，已提交班长验证':'考试未达标，已进入补学');setExamItem(null)}}><Send size={14}/>提交考试</button></footer></section></div>}
  {suggestionOpen&&<div className="learning-modal-backdrop" onClick={()=>setSuggestionOpen(false)}><section className="learning-modal" onClick={event=>event.stopPropagation()}><header><div><span>员工建议箱</span><h2>把一线问题变成改进输入</h2><p>培训岗位将在1个工作日内受理并回传结果。</p></div><button aria-label="关闭建议" onClick={()=>setSuggestionOpen(false)}><X size={18}/></button></header><div><label>建议标题<input value={suggestionTitle} onChange={event=>setSuggestionTitle(event.target.value)}/></label><label>事实与建议<textarea value={suggestionDetail} onChange={event=>setSuggestionDetail(event.target.value)}/></label></div><footer><button className="secondary" onClick={()=>setSuggestionOpen(false)}>取消</button><button className="primary" disabled={busy||!suggestionTitle.trim()||suggestionDetail.trim().length<10} onClick={submitSuggestion}><Send size={14}/>提交培训岗位</button></footer></section></div>}
 </section>
}

export function LeaderLearningApprovals({state,setState,notify}:{state:WorkflowState;setState:StateSetter;notify:Notify}){
 const {busy,run}=useLearningAction(setState,notify)
 const assignments=state.learning.assignments.filter(item=>item.status==='leader_verification')
 const reviews=state.learning.growthReviews.filter(item=>item.status==='leader_pending')
 const total=assignments.length+reviews.length
 return <><div className="leader-learning-head"><div><span>班长学习效果验收</span><h2>考试通过不等于业务改善，班长必须用录音和指标做最后验证</h2></div><em>{total}项待我验证</em></div>{!total?<div className="learning-empty"><CheckCircle2 size={28}/><p>当前没有待班长验证的学习或成长任务。</p></div>:<div className="leader-learning-list">
  {assignments.map(item=><article key={item.id}><span><BookOpenCheck size={20}/></span><div><b>个人学习效果</b><h3>{item.employeeName} · {item.title}</h3><p>考试 {item.score}/{item.targetScore}分 · 目标：{item.improvementTarget}</p><small>员工复盘：{item.reflection}</small></div><button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.learningAssignmentAction(item.id,'leader','leader_verify',{comment:'已抽查2通最新录音，关键步骤执行完整，目标指标进入7日观察，确认本次学习有效。'}),'学习效果已验证并回传员工与培训岗')}><ClipboardCheck size={14}/>验证并关闭</button></article>)}
  {reviews.map(review=><article key={review.id}><span><Target size={20}/></span><div><b>{review.milestone}日成长评估</b><h3>{review.employeeName} · 下一阶段目标确认</h3><p>{review.trainingComment}</p><small>{review.metrics.map(metric=>`${metric.label} ${metric.actual}${metric.unit}/${metric.target}${metric.unit}`).join(' · ')}</small></div><button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.growthReviewAction(review.id,'leader','leader_close','下一阶段以一次解决率达到88%、重复来电率降至4.5%以内为目标，每周复盘2通录音。'),'成长目标已确认并回传员工与培训岗')}><CheckCircle2 size={14}/>确认目标并关闭</button></article>)}
 </div>}</>
}
