import { useState } from 'react'
import { WorkflowState, workflowApi } from '../data/workflowApi'
import { AlertTriangle, ArrowUpRight, BarChart3, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileBarChart, Gauge, ListChecks, Plus, RefreshCw, Target, Users } from './Icons'

type Runner=(action:()=>Promise<WorkflowState>,success:string)=>void
const fmt=(value:string)=>new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})
const remainingDays=(date:string)=>{
 const [year,month,day]=date.split('-').map(Number)
 const today=new Date(),todayUtc=Date.UTC(today.getFullYear(),today.getMonth(),today.getDate())
 return Math.max(0,Math.ceil((Date.UTC(year,month-1,day)-todayUtc)/(24*60*60*1000)))
}
const roleLabel:Record<string,string>={manager:'客服经理',supervisor:'客服主管',hrbp:'HRBP经理',quality:'质检专员',training:'培训主管',director:'运营总监'}
const authorizedMarginText=(value:string)=>value.includes('毛利率')?value.replace(/\d+(?:\.\d+)?(?:%|个百分点|pp)/g,'待授权'):value

export function SupervisorOperationsHub({state,busy,run}:{state:WorkflowState;busy:boolean;run:Runner}){
 const plan=state.governance.shiftPlans[0],route=state.governance.skillRoutes[0]
 const [effect,setEffect]=useState(route?.targetAnswerRate||89)
 const gap=plan?.teams.filter(item=>item.gap>0).reduce((sum,item)=>sum+item.gap,0)||0
 const statusText:Record<string,string>={draft:'待提交',manager_pending:'经理审批中',published:'已发布',returned:'退回调整',executing:'执行中',closed:'验效达标'}
 return <section className="panel supervisor-production-hub">
  <header><div><span>现场生产控制塔 · 数据驱动调度</span><h2>排班先保供给，技能路由必须验效果</h2><p>所有调整经过安全线校验、经理审批和结果回填，避免“发出指令就算完成”。</p></div><em>主管待办 {(plan&&['draft','returned'].includes(plan.status)?1:0)+(route&&['draft','returned','executing'].includes(route.status)?1:0)}</em></header>
  <div className="supervisor-production-metrics">
   <div><span>明日需求</span><strong>{plan?.required||0}人</strong><small>已排 {plan?.scheduled||0}人</small></div>
   <div className={gap?'risk':''}><span>待补缺口</span><strong>{gap}人</strong><small>{gap?'需跨班/技能补位':'已平衡'}</small></div>
   <div><span>路由目标</span><strong>{route?.targetAnswerRate||0}%</strong><small>基线 {route?.baselineAnswerRate||0}%</small></div>
   <div className={route?.status==='closed'?'good':''}><span>实际结果</span><strong>{route?.actualAnswerRate?`${route.actualAnswerRate}%`:'待回填'}</strong><small>{route?statusText[route.status]:''}</small></div>
  </div>
  <div className="supervisor-production-grid">
   {plan&&<article className="production-card"><header><span><CalendarDays size={17}/></span><div><b>{plan.id}</b><h3>{plan.date} 全区域排班计划</h3><p>{plan.area} · 目标覆盖率 ≥{plan.targetCoverage}%</p></div><em className={plan.status}>{statusText[plan.status]}</em></header><div className="team-gap-list">{plan.teams.map(team=><div className={team.gap>0?'risk':team.gap<0?'surplus':''} key={team.team}><strong>{team.team.replace('普通客服一区·','')}</strong><span>{team.scheduled}/{team.required}</span><b>{team.gap>0?`缺${team.gap}`:team.gap<0?`余${Math.abs(team.gap)}`:'平衡'}</b></div>)}</div><p className="production-comment">{plan.result||plan.comment}</p>{['draft','returned'].includes(plan.status)&&<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.governanceShiftPlanAction(plan.id,'supervisor','submit',plan.comment),'排班计划已提交经理审批')}><ClipboardCheck size={14}/>提交经理审批</button>}</article>}
   {route&&<article className="production-card route"><header><span><Gauge size={17}/></span><div><b>{route.id} · {route.source}</b><h3>{route.fromSkill} → {route.toSkill}</h3><p>{route.people}人 · {route.window} · 调出侧保护率{route.sourceProtectionAfter}%</p></div><em className={route.status}>{statusText[route.status]||route.status}</em></header><div className="route-effect"><div><span>调整前</span><strong>{route.baselineAnswerRate}%</strong></div><ChevronRight size={16}/><div><span>目标</span><strong>{route.targetAnswerRate}%</strong></div><ChevronRight size={16}/><div><span>实际</span><strong>{route.actualAnswerRate?`${route.actualAnswerRate}%`:'待观察'}</strong></div></div><p className="production-comment">{route.result||'经理批准后执行，窗口结束必须回填实际接通率，未达标自动返回改进。'}</p>{['draft','returned'].includes(route.status)&&<button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.governanceSkillRouteAction(route.id,'supervisor','submit',{comment:'调出侧高于95%保护线，申请执行技能路由调整'}),'技能路由方案已提交经理审批')}><ArrowUpRight size={14}/>重新提交方案</button>}{route.status==='executing'&&<div className="effect-submit"><label>窗口实际接通率<input type="number" min="0" max="100" step=".1" value={effect} onChange={event=>setEffect(Number(event.target.value))}/><span>%</span></label><button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.governanceSkillRouteAction(route.id,'supervisor','submit_effect',{actualAnswerRate:effect}),'调度效果已回填，系统完成目标校验')}><CheckCircle2 size={14}/>提交验效</button></div>}</article>}
  </div>
 </section>
}

export function ManagerGovernanceApprovals({state,busy,run}:{state:WorkflowState;busy:boolean;run:Runner}){
 const plans=state.governance.shiftPlans.filter(item=>item.status==='manager_pending')
 const routes=state.governance.skillRoutes.filter(item=>item.status==='manager_pending')
 const returned=state.governance.budgets.filter(item=>item.status==='returned')
 const cross=state.governance.crossDepartmentItems.filter(item=>item.targetRole==='manager'&&!['closed','director_verification'].includes(item.status))
 const [comment,setComment]=useState('缺口由6班跨班支援1人、灵活班补位4人，发布后由主管按半小时接通率验效。')
 const [result,setResult]=useState('已完成两份附件的汇总范围与31项指标编码核对，确认H1收入Gap及H2月均追回目标，责任分解清单已归档。')
 return <div className="governance-approval-page"><div className="governance-approval-head"><div><span>主管方案 → 经理审批 → 现场验效</span><h2>生产安全线与跨部门执行审批</h2></div><em>{plans.length+routes.length+returned.length+cross.length}项待处理</em></div>
  <label className="governance-global-comment">审批意见<textarea value={comment} onChange={event=>setComment(event.target.value)}/></label>
  <div className="governance-approval-list">
   {plans.map(plan=><article key={plan.id}><span className="governance-icon"><CalendarDays size={18}/></span><div><b>排班计划 · {plan.id}</b><h3>{plan.area} · {plan.date}</h3><p>需求{plan.required}人，已排{plan.scheduled}人，班组缺口{plan.teams.filter(item=>item.gap>0).reduce((sum,item)=>sum+item.gap,0)}人；目标覆盖率{plan.targetCoverage}%</p></div><aside><button className="secondary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceShiftPlanAction(plan.id,'manager','manager_return',comment),'排班计划已退回主管调整')}>退回</button><button className="primary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceShiftPlanAction(plan.id,'manager','manager_approve',comment),'排班计划已批准并通知主管、班长')}>批准发布</button></aside></article>)}
   {routes.map(route=><article key={route.id}><span className="governance-icon route"><Gauge size={18}/></span><div><b>技能路由 · {route.id}</b><h3>{route.fromSkill} → {route.toSkill}</h3><p>{route.people}人 / {route.window}；预计接通率{route.baselineAnswerRate}%→{route.targetAnswerRate}%，调出侧保护率{route.sourceProtectionAfter}%</p></div><aside><button className="secondary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceSkillRouteAction(route.id,'manager','manager_return',{comment}),'技能路由已退回主管')}>退回</button><button className="primary" disabled={busy} onClick={()=>run(()=>workflowApi.governanceSkillRouteAction(route.id,'manager','manager_approve',{comment}),'技能路由已批准，主管进入执行和验效')}>批准执行</button></aside></article>)}
   {returned.map(item=><article key={item.id}><span className="governance-icon risk"><RefreshCw size={18}/></span><div><b>总监退回 · {item.id}</b><h3>{item.project}</h3><p>{item.directorComment}</p></div><aside><button className="primary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceBudgetAction(item.id,'manager','manager_submit',comment),'已补充材料并重新提交总监')}>补充后重提</button></aside></article>)}
   {cross.map(item=><article className="cross-result-card" key={item.id}><span className="governance-icon cross"><Users size={18}/></span><div><b>总监跨部门协同 · {item.id}</b><h3>{item.title}</h3><p>{item.detail}</p><small>验收目标：{item.target}</small><textarea value={result} onChange={event=>setResult(event.target.value)}/></div><aside><button className="primary" disabled={busy||result.trim().length<10} onClick={()=>run(()=>workflowApi.governanceCrossDepartmentAction(item.id,'manager','submit_result',result),'协同结果已提交总监验收')}>提交总监验收</button></aside></article>)}
   {!plans.length&&!routes.length&&!returned.length&&!cross.length&&<div className="governance-empty"><CheckCircle2 size={28}/><h3>当前生产审批已清零</h3><p>新排班、技能路由或总监协同到达后会在此提醒。</p></div>}
  </div>
 </div>
}

export function RoleCrossDepartmentTasks({role,state,busy,run}:{role:'hrbp'|'quality'|'training'|'supervisor';state:WorkflowState;busy:boolean;run:Runner}){
 const items=state.governance.crossDepartmentItems.filter(item=>item.targetRole===role)
 const [result,setResult]=useState('已联合相关岗位完成数据核对和问题复盘，形成责任清单、阶段目标与7日跟踪计划，证据已归档。')
 return <div className="governance-approval-page"><div className="governance-approval-head"><div><span>总监下发 → 专业岗位执行 → 总监验收</span><h2>{roleLabel[role]}跨部门协同任务</h2></div><em>{items.filter(item=>!['closed','director_verification'].includes(item.status)).length}项待执行</em></div><div className="governance-approval-list role-cross-list">{items.map(item=><article className="cross-result-card" key={item.id}><span className="governance-icon cross"><Users size={18}/></span><div><b>{item.id} · {item.targetDepartment}</b><h3>{item.title}</h3><p>{item.detail}</p><small>验收目标：{item.target} · 截止{fmt(item.dueAt)}</small>{item.result&&<em>已提交：{item.result}</em>}{['target_pending','target_doing','returned'].includes(item.status)&&<textarea value={result} onChange={event=>setResult(event.target.value)}/>}</div><aside>{item.status==='target_pending'&&<button className="secondary" disabled={busy} onClick={()=>run(()=>workflowApi.governanceCrossDepartmentAction(item.id,role,'start'),'跨部门事项已接收并开始处理')}>接收任务</button>}{['target_pending','target_doing','returned'].includes(item.status)&&<button className="primary" disabled={busy||result.trim().length<10} onClick={()=>run(()=>workflowApi.governanceCrossDepartmentAction(item.id,role,'submit_result',result),'执行结果已提交总监验收')}>提交验收</button>}{item.status==='director_verification'&&<span>等待总监验收</span>}{item.status==='closed'&&<span className="cross-closed"><CheckCircle2 size={14}/>已闭环</span>}</aside></article>)}{!items.length&&<div className="governance-empty"><CheckCircle2 size={28}/><h3>暂无跨部门协同</h3><p>总监下发到本岗位后，会在此进入计时和执行闭环。</p></div>}</div></div>
}

export function DirectorGovernanceHub({state,busy,run}:{state:WorkflowState;busy:boolean;run:Runner}){
 const [tab,setTab]=useState<'decision'|'meeting'|'cross'>('decision')
 const [comment,setComment]=useState('同意按本次预测执行；客服经理每日18:00回传回款确认、成本压降和毛利恢复进展，偏差扩大时立即升级。')
 const [meetingSummary,setMeetingSummary]=useState(state.governance.meetings[0]?.summary||'')
 const [crossResult,setCrossResult]=useState('验收通过，差异清单已覆盖全部金额并明确客户确认节点，纳入次日经营复盘。')
 const [newTitle,setNewTitle]=useState('新工入列后30日稳定与产能联合复盘')
 const [newDetail,setNewDetail]=useState('请HRBP联合培训、业务经理核对新工到岗、离职风险、产能成长和辅导动作，形成批次级问题清单。')
 const [newTarget,setNewTarget]=useState('22名新工档案、稳定风险和产能成长状态100%明确，形成责任人和7日改善计划')
 const budgets=state.governance.budgets,contracts=state.governance.contracts,meeting=state.governance.meetings[0]
 const cross=state.governance.crossDepartmentItems
 const pending=budgets.filter(item=>item.status==='director_pending').length+cross.filter(item=>item.status==='director_verification').length+(meeting?.status==='draft'?1:0)
 return <section className="panel director-governance-hub"><header><div><span>总监治理闭环 · 经营结果与组织动作同源</span><h2>预算负责决策，合同负责查阅与到期提醒</h2><p>预算、例会与协同事项形成决策闭环；三份基地合同作为只读台账展示，不进入总监审批流。</p></div><em>{pending}项总监待决策</em></header>
  <nav><button className={tab==='decision'?'active':''} onClick={()=>setTab('decision')}><BriefcaseBusiness size={15}/>预算决策与合同台账{budgets.filter(item=>item.status==='director_pending').length>0&&<b>{budgets.filter(item=>item.status==='director_pending').length}</b>}</button><button className={tab==='meeting'?'active':''} onClick={()=>setTab('meeting')}><FileBarChart size={15}/>经营会议{meeting?.status==='draft'&&<b>1</b>}</button><button className={tab==='cross'?'active':''} onClick={()=>setTab('cross')}><Users size={15}/>跨部门协同{cross.filter(item=>item.status==='director_verification').length>0&&<b>{cross.filter(item=>item.status==='director_verification').length}</b>}</button></nav>
  {tab==='decision'&&<div className="director-decision-grid">
   <label className="director-decision-comment">总监预算决策意见<textarea value={comment} onChange={event=>setComment(event.target.value)}/></label>
   {budgets.map(item=><article key={item.id}><header><span><BarChart3 size={17}/></span><div><b>{item.id} · {item.month}</b><h3>{item.project}预算达成与追回决策</h3></div><em className={item.status}>{item.status==='director_pending'?'待总监决策':item.status==='active'?'执行中':'已退回'}</em></header><div className="decision-kpis"><span>H1收入预算<strong>{item.revenueTarget}万</strong></span><span>H1收入实际<strong>{item.forecastRevenue}万</strong></span><span>H1成本预算<strong>{item.costBudget}万</strong></span><span>实际毛利率<strong>待授权</strong></span></div><p>{authorizedMarginText(item.managerComment)}</p>{item.status==='director_pending'&&<footer><button className="secondary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceBudgetAction(item.id,'director','director_return',comment),'经营预测已退回经理补充')}>退回重测</button><button className="primary" disabled={busy||!comment.trim()} onClick={()=>run(()=>workflowApi.governanceBudgetAction(item.id,'director','director_approve',comment),'预算与经营动作已批准并回传经理')}>批准执行</button></footer>}</article>)}
   {contracts.map(item=><article className="contract-ledger-card" key={item.id}><header><span><BriefcaseBusiness size={17}/></span><div><b>{item.id} · {item.customer}</b><h3>{item.project}合同</h3></div><em className="active">合同有效</em></header><div className="contract-facts"><div><span>合同金额</span><strong>{item.amount===null?'暂无固定合同额':`${item.amount.toLocaleString('zh-CN')}万`}</strong></div><div><span>结费方式</span><strong>{item.billingMode}</strong></div><div><span>合同周期</span><strong>{item.startDate} — {item.endDate}</strong></div></div><div className="contract-expiry"><CalendarDays size={17}/><div><b>到期提醒</b><span>距合同到期还有 {remainingDays(item.endDate)} 天，到期日 {item.endDate}</span></div></div><p>{item.managerComment}</p><footer className="contract-readonly"><CheckCircle2 size={15}/>总监只读查阅 · 无需审批</footer></article>)}
  </div>}
  {tab==='meeting'&&meeting&&<div className="meeting-production"><article><header><div><b>{meeting.id} · {meeting.date}</b><h3>{meeting.title}</h3></div><em className={meeting.status}>{meeting.status==='draft'?'待发布':'已归档'}</em></header><label>会议总结<textarea value={meetingSummary} onChange={event=>setMeetingSummary(event.target.value)}/></label><div className="meeting-conclusions"><strong>经营结论</strong>{meeting.conclusions.map((item,index)=><p key={item}><span>{index+1}</span>{item}</p>)}</div><div className="meeting-actions"><strong>会后行动</strong>{meeting.actions.map(action=><p key={action.id}><span>{roleLabel[action.ownerRole]}</span><b>{action.title}</b><em>{action.target}</em><small>{fmt(action.dueAt)}</small></p>)}</div>{meeting.status==='draft'?<button className="primary" disabled={busy||meetingSummary.trim().length<20} onClick={()=>run(()=>workflowApi.governanceMeetingAction(meeting.id,meetingSummary),'经营会议纪要已归档，行动已进入责任岗位PDCA')}><ListChecks size={15}/>发布纪要并下发PDCA</button>:<div className="meeting-published"><CheckCircle2 size={18}/>已于 {fmt(meeting.publishedAt)} 归档并下发 {meeting.actions.length} 项行动</div>}</article></div>}
  {tab==='cross'&&<div className="cross-department-grid"><section><header><span>跨部门事项台账</span><h3>总监下发、岗位执行、总监验收</h3></header>{cross.map(item=><article key={item.id}><div><b>{item.id} · {roleLabel[item.targetRole]}</b><h3>{item.title}</h3><p>{item.detail}</p><small>目标：{item.target} · 截止{fmt(item.dueAt)}</small>{item.result&&<em>执行结果：{item.result}</em>}</div><span className={item.status}>{item.status==='director_verification'?'待总监验收':item.status==='closed'?'已关闭':item.status==='returned'?'退回补充':'执行中'}</span>{item.status==='director_verification'&&<aside><textarea value={crossResult} onChange={event=>setCrossResult(event.target.value)}/><button className="secondary" disabled={busy||!crossResult.trim()} onClick={()=>run(()=>workflowApi.governanceCrossDepartmentAction(item.id,'director','director_return',crossResult),'跨部门事项已退回补充')}>退回</button><button className="primary" disabled={busy||!crossResult.trim()} onClick={()=>run(()=>workflowApi.governanceCrossDepartmentAction(item.id,'director','director_verify',crossResult),'跨部门事项已验收关闭')}>验收关闭</button></aside>}</article>)}</section><aside className="cross-create"><header><span><Plus size={15}/></span><div><b>新建总监协同</b><p>当前示例下发至HRBP经理</p></div></header><label>事项标题<input value={newTitle} onChange={event=>setNewTitle(event.target.value)}/></label><label>事实说明<textarea value={newDetail} onChange={event=>setNewDetail(event.target.value)}/></label><label>验收目标<textarea value={newTarget} onChange={event=>setNewTarget(event.target.value)}/></label><button className="primary" disabled={busy||!newTitle.trim()||newDetail.trim().length<10||!newTarget.trim()} onClick={()=>run(()=>workflowApi.createCrossDepartmentItem({title:newTitle,targetRole:'hrbp',targetDepartment:'HAC支持部 · 人力资源',detail:newDetail,target:newTarget,dueAt:new Date(Date.now()+24*60*60*1000).toISOString()}),'跨部门协同已下发HRBP经理并进入任务提醒')}><Target size={14}/>下发并计时</button></aside></div>}
 </section>
}
