import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './auth.css'
import './account-menu.css'
import './quality.css'
import './training.css'
import './hrbp.css'
import './assistant.css'
import './ai-settings.css'
import './workflow-quality.css'
import './workforce.css'
import './learning.css'
import './operations.css'
import './salary.css'
import './lean-pdca.css'
import './development.css'
import './team-actions.css'
import './excellence.css'
import './budget-achievement.css'
import './budget-focus-light.css'
import './morning-briefing-hub.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>
)
